version: 0.2

env:
  shell:
    - /bin/bash
    - -e
    - -o pipefail
  variables:
    PRJ_NAME="codebuild-test"
    DIRECTORY_TO_BUILD="blog"
phases:
  install:
    commands:
      - echo Fetching Git metadata...
      - CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - echo "Files changed in this commit: $CHANGED_FILES"
      - |
        IGNORE_LIST=($(cat build-quasar-ignore.txt))
        for file in $CHANGED_FILES
        do
          if [[ ${file} == ${DIRECTORY_TO_BUILD}/* && ! " ${IGNORE_LIST[@]} " =~ " ${file} " ]]; then
            echo "File ${file} is not in the ignore list and is in the ${DIRECTORY_TO_BUILD}. Proceeding with build..."
            PROCEED_BUILD="true"
            break
          fi
        done
        if [[ -z ${PROCEED_BUILD} ]]; then
          echo "Only ignored files were modified or no changes in ${DIRECTORY_TO_BUILD}. Exiting build..."
          exit 0
        fi
      - npm install
      - npm install -g @quasar/cli
      - apt-get update -y
      - RELEASE_BUCKET=$(aws ssm get-parameter --name "/${PRJ_NAME}/release_bucket" --query "Parameter.Value" --output text)}
      - CLOUDFRONT_DISTRIBUTION_ID=$(aws ssm get-parameter --name "/${PRJ_NAME}/cloudfront_dist_id" --query "Parameter.Value" --output text)}
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm ci
      - echo "$(hostname -i) local" >> /etc/hosts
      - cat /etc/hosts
  build:
    commands:
      - echo Build Phase
      - cd blog
      - quasar build
  post_build:
    commands:
      - aws s3 sync dist/spa s3://${RELEASE_BUCKET} --delete
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
