version: 0.2

env:
  shell:
    - /bin/bash
    - -e
    - -o pipefail
  variables:
    PRJ_NAME="codebuild-test"

phases:
  install:
#    runtime-versions:
#      python: 3.9
    commands:
#      - pip install -r requirements.txt
      - npm install
      - npm install -g @quasar/cli
      - apt-get update -y
      - RELEASE_BUCKET=$(aws ssm get-parameter --name "/${PRJ_NAME}/release_bucket" --query "Parameter.Value" --output text)}
      - CLOUDFRONT_DISTRIBUTION_ID=$(aws ssm get-parameter --name "/${PRJ_NAME}/cloudfront_dist_id" --query "Parameter.Value" --output text)}
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm ci
      - echo "$(hostname -i) local" >> /etc/hosts
      - cat /etc/hosts
  build:
    commands:
      - echo Build Phase
      - quasar build
  post_build:
    commands:
      - aws s3 sync dist/spa s3://${RELEASE_BUCKET} --delete
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
