version: 0.2

env:
  variables:
    CLOUDFRONT_DISTRIBUTION_ID: "E38PYBVO6WWGX"
    WEB_RELEASE_BUCKET: "hello-world-web-dev"
phases:
  install:
#    runtime-versions:
#      python: 3.9
    commands:
      - pip install -r requirements.txt
      - npm install
      - npm install -g @quasar/cli
      - apt-get update -y
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm ci
      - echo "$(hostname -i) local" >> /etc/hosts
      - cat /etc/hosts
  build:
    commands:
      - echo Build Phase
      - quasar build
  post_build:
    commands:
      - aws s3 sync dist/spa s3://${WEB_RELEASE_BUCKET} --delete
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/spa'